<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_6565af01867da',
    'title' => __('Webhooks', 'webhooks-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_6565af01d3812',
            'label' => __('Webhooks', 'webhooks-manager'),
            'name' => 'webhooks',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Lägg till rad', 'webhooks-manager'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_6565af98e3ba4',
                    'label' => __('Payload URL', 'webhooks-manager'),
                    'name' => 'payload_url',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => __('Target url used for the request made when the selected hook is fired. The url can contain placeholders that will be replaced with hook arguments before request is sent. Placeholder format is the "$" character followed by the index of the hooks parameter. E.g. to use the first parameter in the hook, the placeholder should be "$1".
Note that only hook arguments of type string or int can be used by placeholders, all other will be omitted.', 'webhooks-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '75',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => __('https://my.client.site/api/$1', 'webhooks-manager'),
                    'parent_repeater' => 'field_6565af01d3812',
                ),
                1 => array(
                    'key' => 'field_6565afd8e3ba5',
                    'label' => __('HTTP Method', 'webhooks-manager'),
                    'name' => 'http_method',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => __('HTTP method used when making the request to the given payload url.', 'webhooks-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                    ),
                    'default_value' => __('POST', 'webhooks-manager'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'parent_repeater' => 'field_6565af01d3812',
                ),
                2 => array(
                    'key' => 'field_6565b01fe3ba6',
                    'label' => __('Action', 'webhooks-manager'),
                    'name' => 'action',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => __('WordPress hook that determines when to fire the webhook.', 'webhooks-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'parent_repeater' => 'field_6565af01d3812',
                ),
                3 => array(
                    'key' => 'field_6566fe78ee13f',
                    'label' => __('Action Priority', 'webhooks-manager'),
                    'name' => 'action_priority',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => __('Priority passed to add_action for the selected action hook.', 'webhooks-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 10,
                    'min' => 0,
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_6565af01d3812',
                ),
                4 => array(
                    'key' => 'field_6565b15fe3ba7',
                    'label' => __('Send payload', 'webhooks-manager'),
                    'name' => 'should_send_payload',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => __('Wether to send the data passed to the selected action hook in the request to the payload ur or not.', 'webhooks-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'parent_repeater' => 'field_6565af01d3812',
                ),
                5 => array(
                    'key' => 'field_6565b1c6e3ba8',
                    'label' => __('Status', 'webhooks-manager'),
                    'name' => 'is_active',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui_on_text' => __('Active', 'webhooks-manager'),
                    'ui_off_text' => __('Inactive', 'webhooks-manager'),
                    'ui' => 1,
                    'parent_repeater' => 'field_6565af01d3812',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'webhooks-manager',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));
}