<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_6565af01867da',
    'title' => __('Webhooks', 'webhooks-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_6565af01d3812',
            'label' => __('Webhooks', 'webhooks-manager'),
            'name' => 'webhooks',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Lägg till rad', 'webhooks-manager'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_6565af98e3ba4',
                    'label' => __('Payload URL', 'webhooks-manager'),
                    'name' => 'payload_url',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => __('Target url used for the request made when the selected hook is fired.', 'webhooks-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'parent_repeater' => 'field_6565af01d3812',
                ),
                1 => array(
                    'key' => 'field_6565afd8e3ba5',
                    'label' => __('HTTP Method', 'webhooks-manager'),
                    'name' => 'http_method',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => __('HTTP method used when making the request to the given payload url.', 'webhooks-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'POST' => __('POST', 'webhooks-manager'),
                        'GET' => __('GET', 'webhooks-manager'),
                    ),
                    'default_value' => __('POST', 'webhooks-manager'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'parent_repeater' => 'field_6565af01d3812',
                ),
                2 => array(
                    'key' => 'field_6565b01fe3ba6',
                    'label' => __('Action', 'webhooks-manager'),
                    'name' => 'action',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => __('WordPress hook that determines when to fire the webhook.', 'webhooks-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'deleted_post' => __('deleted_post', 'webhooks-manager'),
                        'post_updated' => __('post_updated', 'webhooks-manager'),
                        'save_post' => __('save_post', 'webhooks-manager'),
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'parent_repeater' => 'field_6565af01d3812',
                ),
                3 => array(
                    'key' => 'field_6565b15fe3ba7',
                    'label' => __('Payload', 'webhooks-manager'),
                    'name' => 'payload',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => __('Wether to send the data passed to the selected action hook in the request to the payload ur or not.', 'webhooks-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '34',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'ALL' => __('All', 'webhooks-manager'),
                        'EMPTY' => __('Empty', 'webhooks-manager'),
                    ),
                    'default_value' => __('ALL', 'webhooks-manager'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'parent_repeater' => 'field_6565af01d3812',
                ),
                4 => array(
                    'key' => 'field_6565b1c6e3ba8',
                    'label' => __('Status', 'webhooks-manager'),
                    'name' => 'status',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui_on_text' => __('Active', 'webhooks-manager'),
                    'ui_off_text' => __('Inactive', 'webhooks-manager'),
                    'ui' => 1,
                    'parent_repeater' => 'field_6565af01d3812',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'webhooks-manager',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));
}